[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "listphile"
version = "0.0.2"
dependencies = []

[project.optional-dependencies]
audio = ["eyed3"]

[tool.setuptools]
packages = ["listphile"]
